---
# Run all tests
stages:
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

# Tests for EPC driver for CRS 11.3
EPC atg-crs 11.3:
  variables:
    EPC_REGION: EPAM-BY2
  stage: Deployment test
  script:
    - molecule test -s cloud-epc-11.3
  tags:
    - delegated

# Tests for AWS driver for CRS 11.3
AWS atg-crs 11.3:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: Deployment test
  script:
    - molecule test -s cloud-aws-11.3
  tags:
    - delegated

# Tests for Docker driver for CRS 11.3
Docker atg-crs 11.3:
  stage: Deployment test
  script:
    - molecule test -s docker-11.3
  tags:
    - docker

# Tests for Docker driver for CRS 11.2
Docker atg-crs 11.1:
  stage: Deployment test
  script:
    - molecule test -s docker-11.2
  tags:
    - docker

# Tests for Docker driver for CRS 11.1
Docker atg-crs 11.1:
  stage: Deployment test
  script:
    - molecule test -s docker-11.1
  tags:
    - docker

# Tests for Docker driver for CRS 10.2.1
Docker atg-crs 10.2.1:
  stage: Deployment test
  script:
    - molecule test -s docker-10.2.1
  tags:
    - docker
