---
- name: "Fetch CRS artifact with {{ transport }} transport"
  include_tasks: "{{ transport_driver }}"
  with_first_found:
    - "fetch/{{ transport }}.yml"
    - "fetch/unknown-transport.yml"
  loop_control:
    loop_var: transport_driver

- name: "Read dynamo_root"
  stat:
    path: "{{ dynamo_root }}"
  register: atg_path

- name: "Get ATG user"
  set_fact:
    atg_user: "{{ atg_path.stat.pw_name }}"
    atg_group: "{{ atg_path.stat.gr_name }}"

- name: "Become section"
  block:
    - name: "Install unzip"
      package:
        name: "unzip"
        state: "present"

    - name: "Extract CRS installer"
      unarchive:
        src: "{{ crs_artifact }}"
        dest: "{{ download_path }}"
        list_files: True
      register: crs_installer

    - name: "Ensure {{ crs_installer.files[0] }} is executable"
      file:
        path: "{{ download_path }}/{{ crs_installer.files[0] }}"
        owner: "{{ atg_user }}"
        group: "{{ atg_group }}"
        mode: "0755"

  become: True

- name: "Set crs_installer_bin"
  set_fact:
    crs_installer_bin: "{{ download_path }}/{{ crs_installer.files[0] }}"

- name: "Create silent install file for Commerce Reference Store {{ crs_version }}"
  template:
    src: "crs_installer.properties.j2"
    dest: "{{ download_path }}/crs_installer_{{ crs_version }}.properties"
  register: crs_silent_install

- name: "Install Commerce Service Center {{ crs_version }}"
  become_user: "{{ atg_user }}"
  command: "{{ crs_installer_bin }} -i silent -f {{ crs_silent_install.dest }}"
  args:
    creates: "{{ crs_config_txt }}"
  become: True
