---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 7
      java_minor_version: 191
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-java/jdk-7u191-linux-x64.tar.gz"
    - role: lean_delivery.jboss
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/app-servers/jboss-eap-6.1.0.zip"
    - role: lean_delivery.atg_platform
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/ATG11.3/Platform/V861209-01.zip"
    - role: ansible-role-atg-crs
      crs_version: "11.3"
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/ATG11.3/CRS/V861211-01.zip"

  vars:
    atg_version: "11.3"
    dynamo_root: "/opt/atg/ATG{{ atg_version }}"
